### ISSUE TITLE
Failing to read any exif data

### ISSUE THREAD

**Issue by NiklasEi** [benib/jekyll-exiftag#7]
I am having trouble getting any exif data using this plugin. Following the example of the readme I use: 
```
{% capture model %}
    {% exiftag model, assets/images, assets/images/image.jpg %}
{% endcapture %}
```

Checking the exif data in the terminal (`identify -verbose image.jpg | grep "exif:"`) gives me a huge list of values including the model tag. But using exiftag I keep getting an empty string from `{{ model | inspect }}`. I tried adding the path to the config or passing nil, since the second parameter is the exact path to the file, but that changes nothing.

Is there anything I might be missing? This plugin should still work, right?

**Comment by benib** [comment]
Hi @NiklasEi 

So I am very late with an answer. Not sure if this is still helpful after months. I haven't used this plugin myself since years. But I believe the third parameter should be just the image filename, not the whole path, so something like
```
{% exiftag model, assets/images, image.jpg %}
```
When I wrote the plugin, I always used it by defining the `img` filename in the YAML front matter and the sources in the config file, so I used it like this: `{% exiftag model %}`.

I do believe the plugin should be still working, but I cannot guarantee. If it works for you I would be very glad if you could comment here to let others know.

**Comment by benib** [comment]
I am not sure, but this might be as well an issue with how exifr is used in this plugin that is solved in this PR I never got around to merge and release: https://github.com/benib/jekyll-exiftag/pull/6

**Comment by NiklasEi** [comment]
Hi @benib 

Thanks for the answer. As far as I remember I could not fix the issue using this plugin and ended up writing my own one ^^ (see [jekyll-exif-data](https://github.com/NiklasEi/jekyll-exif-data))

It uses filters instead of a tag, but the interaction with exifr should be the same. I could compare our implementations and see if something comes up.

**Comment by NiklasEi** [comment]
Looks like the only difference is requiring exifr/jpeg like in #6. You could then also change the dependency in your gemspec to `.add_dependency "exifr", "~> 1.3"`.
